apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAllowedPolicyMemberDomainsConstraint
metadata:
  name: service_accounts_only
spec:
  severity: high
  match:
    target: ["organizations/*"]
  parameters:
    domains:
      - gserviceaccount.com
